name: Test Python Script on Push

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  test-script:
    runs-on: ubuntu-22.04
    if: false 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install
        pip install pymongo
        pip install python-dotenv

    - name: Run Python script
      working-directory: ./webscrape
      run: python3 print.py

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Push hello_world.txt to repository
      working-directory: ./webscrape
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add hello_world.txt
        git commit -m "Add hello_world.txt from workflow"
        git push origin main