name: Test Python On Push

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo
        pip install python-dotenv

    - name: Validate ARINWANG Secret
      run: |
        if [ -z "$ARINWANG" ]; then
          echo "ARINWANG is not set or is empty."
          exit 1
        else
          echo "ARINWANG is set."
        fi
      env:
        MONGODB_URI: ${{ secrets.MONGO_URI }}

    - name: Validate MONGO_URI Secret
      run: |
        if [ -z "$MONGO_URI" ]; then
          echo "MONGO_URI is not set or is empty."
          exit 1
        else
          echo "MONGO_URI is set."
        fi
      env:
        MONGODB_URI: ${{ secrets.MONGO_URI }}

    
    

    - name: Run Python script
      working-directory: ./webscrape
      run: python mongodb.py
